Blastar\FrontUserBundle\Entity\User:
    type: entity
    table: user
    repositoryClass: Blastar\FrontUserBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
        password:
            type: string
            length: 255
        email:
            type: string
            length: 255
        isActive:
            type: boolean
    lifecycleCallbacks: {  }
