Blastar\AdminNewsBundle\Entity\News:
    type: entity
    table: null
    repositoryClass: Blastar\AdminNewsBundle\Entity\NewsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        header:
            type: text
            nullable: true
        content:
            type: text
            nullable: true
        createdAt:
            type: datetime
            column: created_at
        modifiedAt:
            type: datetime
            column: modified_at
        isEnabled:
            type: boolean
            column: is_enabled
        url:
            type: string
            length: 255            
    lifecycleCallbacks: {  }
