Blastar\AdminUserBundle\Entity\User:
    type: entity
    table: admin_user
    repositoryClass: Blastar\AdminUserBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
        salt:
            type: string
            length: 255
        password:
            type: string
            length: 255
        email:
            type: string
            length: 255
        isActive:
            type: boolean
    lifecycleCallbacks: {  }
    manyToMany:
        acl: 
            targetEntity: Blastar\AdminUserBundle\Entity\Role
            joinTable: 
                name: admin_user_has_role
                joinColumns: 
                    user_id: 
                        referencedColumnName: id
                        onDelete: "cascade"
                inverseJoinColumns: 
                    role_id: 
                        referencedColumnName: id      
