Blastar\AdminCategoryBundle\Entity\Category:
    type: entity
    table: category
    repositoryClass: Blastar\AdminCategoryBundle\Entity\CategoryRepository
    gedmo:
        tree:
            type: nested    
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        lft:
            type: integer
            gedmo:
                - treeLeft            
        level:
            type: integer
            gedmo:
                - treeLevel            
        rgt:
            type: integer
            gedmo:
                - treeRight            
        root:
            type: integer
            gedmo:
                - treeRoot            
    lifecycleCallbacks: {  }
    manyToOne:
        parent:
            targetEntity: Blastar\AdminCategoryBundle\Entity\Category
            inversedBy: children
            joinColumn:
                name: parent_id
                referencedColumnName: id
                onDelete: CASCADE
            gedmo:
                - treeParent
    oneToMany:
        children:
            targetEntity: Blastar\AdminCategoryBundle\Entity\Category
            mappedBy: parent
            orderBy:
                lft: ASC