<?php

namespace Blastar\AdminCmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CmsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsRepository extends EntityRepository
{
}
