blastar_front_user_homepage:
    path:     /
    defaults: { _controller: BlastarFrontUserBundle:Default:index }
    
blastar_front_login:
    path:     /login
    defaults: { _controller: BlastarFrontUserBundle:Default:login }
    
blastar_front_login_check:
    path: /login_check
    
blastar_front_logout:
    path: /logout
    
    