blastar_admin_user_homepage:
    path:     /admin
    defaults: { _controller: BlastarAdminUserBundle:Default:index }
blastar_admin_login:
    path:     /admin/login
    defaults: { _controller: BlastarAdminUserBundle:Default:login }
blastar_admin_login_check:
    path: /admin/login_check
blastar_admin_logout:
    path: /admin/logout
# user manager    
blastar_admin_user_manager_list:
    path:     /admin/admins
    defaults: { _controller: BlastarAdminUserBundle:Admins:index }
blastar_admin_user_manager_edit:
    path:     /admin/admins/edit/{id}
    defaults: { _controller: BlastarAdminUserBundle:Admins:edit }
blastar_admin_user_manager_save:
    path:     /admin/admins/save/{id}
    defaults: { _controller: BlastarAdminUserBundle:Admins:save }
    
# categories
blastar_admin_categories_list:
    path:     /admin/categories
    defaults: { _controller: BlastarAdminUserBundle:Cms:index }




# cms
blastar_admin_cms_list:
    path:     /admin/cms
    defaults: { _controller: BlastarAdminUserBundle:Cms:index }

blastar_admin_cms_edit:
    path:     /admin/cms/edit/{id}/{parentid}
    defaults: { _controller: BlastarAdminUserBundle:Cms:edit, parentid: 0 }

blastar_admin_cms_save:
    path:     /admin/cms/save/{id}/{parentid}
    defaults: { _controller: BlastarAdminUserBundle:Cms:save, parentid: 0 }

blastar_admin_cms_remove:
    path:     /admin/cms/remove/{id}
    defaults: { _controller: BlastarAdminUserBundle:Cms:remove }

    
    
    
    
    
    