
# user manager    
blastar_admin_user_manager_list:
    path:     /
    defaults: { _controller: BlastarAdminUserBundle:Admins:index }
blastar_admin_user_manager_edit:
    path:     /edit/{id}
    defaults: { _controller: BlastarAdminUserBundle:Admins:edit }
blastar_admin_user_manager_save:
    path:     /save/{id}
    defaults: { _controller: BlastarAdminUserBundle:Admins:save }


    
    
    
    
    