blastar_admin_cms_list:
    path:     /
    defaults: { _controller: BlastarAdminCmsBundle:Cms:index }
    
blastar_admin_cms_edit:
    path:     /edit/{id}
    defaults: { _controller: BlastarAdminCmsBundle:Cms:edit }

blastar_admin_cms_save:
    path:     /save/{id}
    defaults: { _controller: BlastarAdminCmsBundle:Cms:save }

blastar_admin_cms_remove:
    path:     /remove/{id}
    defaults: { _controller: BlastarAdminCmsBundle:Cms:remove }    
    
    