<?php

namespace Admin\ProductBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductPriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductPriceRepository extends EntityRepository
{
}
